// <auto-generated />
using System;
using InvestmentsApp.Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentsApp.Backend.Migrations
{
    [DbContext(typeof(InvestmentsAppContext))]
    [Migration("20241213184727_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InvestmentsApp.Backend.Models.Investmetn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdTypeInvestment")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ImporteFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tikcker")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdTypeInvestment");

                    b.HasIndex("Tikcker");

                    b.ToTable("Investmetns");
                });

            modelBuilder.Entity("InvestmentsApp.Backend.Models.TypeInvestment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Baja")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TypeInvestments");
                });

            modelBuilder.Entity("InvestmentsApp.Backend.Models.Investmetn", b =>
                {
                    b.HasOne("InvestmentsApp.Backend.Models.TypeInvestment", "TypeInvestment")
                        .WithMany("Investemnts")
                        .HasForeignKey("IdTypeInvestment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeInvestment");
                });

            modelBuilder.Entity("InvestmentsApp.Backend.Models.TypeInvestment", b =>
                {
                    b.Navigation("Investemnts");
                });
#pragma warning restore 612, 618
        }
    }
}
